name: Dast Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Instalar Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # 4. Levantar backend
    - name: Start backend
      run: |
        cd backend &&
        npm install &&
        npm start &
        sleep 15
    # 5. Levantar frontend
    - name: Start frontend
      run: |
        cd frontend &&
        npm install &&
        npm start &
        sleep 15
    # Preparar carpeta y permisos para que el contenedor ZAP pueda escribir
    - name: Prepare DAST reports directory
      run: |
        mkdir -p reports/DAST
        chmod -R a+rwX reports/DAST || true
        rm -f reports/DAST/zap-report.html reports/DAST/zap.json reports/DAST/zap-report-backend.html reports/DAST/zap-backend.json
    # 8. Ejecutar OWASP ZAP frontend
    - name: Run OWASP ZAP full scan
      run: |
        docker run --network="host" \
          --user root \
          -v $(pwd):/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://localhost:3000 \
          -j \
          -r reports/DAST/zap-report.html \
          -x reports/DAST/zap-frontend.xml \
          -I

    # 9. Ejecutar OWASP ZAP backend
    - name: Run OWASP ZAP full scan on backend
      run: |
        docker run --network="host" \
          --user root \
          -v $(pwd):/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://localhost:3001 \
          -n /zap/wrk/zap.context \
          -r reports/DAST/zap-report-backend.html \
          -x reports/DAST/zap-backend.xml \
          -z "-config spider.seedUrls=/zap/wrk/zap-urls.txt" \
          -I

    # 10. Guardar reportes
    - name: Upload ZAP reports
      uses: actions/upload-artifact@v4
      with:
        name: zap-reports
        path: reports/DAST/