name: Dast Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Instalar Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # 4. Levantar backend
    - name: Start backend
      run: |
        cd backend &&
        npm install &&
        npm start &
        sleep 15
    # 5. Levantar frontend
    - name: Start frontend
      run: |
        cd frontend &&
        npm install &&
        npm start &
        sleep 15
    #Permisos para generar reporte owasp zap    
    - name: Fix workspace permissions
      run: chmod -R 777 .
    # 7. Ejecutar OWASP ZAP
    - name: Run OWASP ZAP full scan
      run: |
        docker run --network="host" \
          -v $(pwd):/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://localhost:3000 \
          -j \
          -r zap-report.html \
          -J zap.json \
          -I

    - name: Run OWASP ZAP full scan on backend
      run: |
        docker run --network="host" \
          -v $(pwd):/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://localhost:3001 \
          -n /zap/wrk/zap.context \
          -r zap-report-backend.html \
          -J zap-backend.json \
          -z "-config spider.seedUrls=/zap/wrk/zap-urls.txt" \
          -I

    # 8. Guardar reporte
    - name: Upload ZAP reports
      uses: actions/upload-artifact@v4
      with:
        name: zap-reports
        path: |
          zap-report.html
          zap-report-backend.html
          zap.json
          zap-backend.json